FROM golang:alpine as builder


RUN apk update && apk add --no-cache git && apk add --no-cache bash && apk add build-base

WORKDIR /app
COPY ./go.mod .
RUN go mod download


COPY . .

RUN go get -d -v ./...

RUN go install -v ./...

RUN go build -o ./build .

FROM alpine:edge
WORKDIR /app

COPY --from=builder /app/build ./build
EXPOSE 8010

ENTRYPOINT ["./build"]