apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.label }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
      - name: {{ .Values.label }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 8010
        env:
        - name: DB_HOST
          value: postgres-service
        - name: ALLOW_ORIGIN
          value: {{ .Values.clusterIP }}:{{ .Values.nodePortFront }}
      
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label }}-service
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: 8010
      nodePort: {{ .Values.nodePortBackend }}