definitions:
  controllers.AccountReq:
    properties:
      bio:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      phone:
        maxLength: 11
        minLength: 11
        type: string
    type: object
  controllers.ErrResponse:
    properties:
      error:
        type: string
      status_code:
        type: integer
    type: object
  controllers.LinkReq:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  controllers.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  controllers.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - username
    type: object
  controllers.SuccessResponse:
    properties:
      data: {}
      status_code:
        type: integer
    type: object
  controllers.UserImageReq:
    type: object
host: localhost:8010
info:
  contact: {}
  description: platform that allows users to share social media profiles, or other
    important links defined in a single place
  title: LinkTree
  version: "1.0"
paths:
  /account/add_photo:
    post:
      consumes:
      - multipart/form-data
      description: Upload User Image
      parameters:
      - description: image
        in: body
        name: UserImageReq
        required: true
        schema:
          $ref: '#/definitions/controllers.UserImageReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Upload User Image
      tags:
      - account
  /account/create_link_tree_url:
    get:
      consumes:
      - application/json
      description: create link tree url
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: create link tree url
      tags:
      - account
  /account/delete_account:
    delete:
      consumes:
      - application/json
      description: delete account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Delete Account
      tags:
      - account
  /account/edit_account:
    put:
      consumes:
      - application/json
      description: Edit Account data
      parameters:
      - description: first name, last name, phone, bio
        in: body
        name: AccountReq
        required: true
        schema:
          $ref: '#/definitions/controllers.AccountReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Edit Account
      tags:
      - account
  /account/get_account:
    get:
      consumes:
      - application/json
      description: Get Account data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Get Account
      tags:
      - account
  /analytics/get_analytics/{user_id}:
    get:
      consumes:
      - application/json
      description: Get Analytics properties of how many users view the tree links
        and their users name
      parameters:
      - description: user ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Get Analytics
      tags:
      - analytics
  /auth/login:
    post:
      consumes:
      - application/json
      description: returns users token after login
      parameters:
      - description: email and password
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      summary: Login
      tags:
      - auth
  /auth/logout:
    get:
      consumes:
      - application/json
      description: removes user token from cookies
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
      security:
      - basic: []
      summary: Logout
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: creates user account
      parameters:
      - description: first name, last name, email, username and password
        in: body
        name: RegisterRequest
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      summary: Register
      tags:
      - auth
  /link/create_link:
    post:
      consumes:
      - application/json
      description: Create Link
      parameters:
      - description: link attribute
        in: body
        name: LinkReq
        required: true
        schema:
          $ref: '#/definitions/controllers.LinkReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Create Link
      tags:
      - link
  /link/delete_link/{link_id}:
    delete:
      consumes:
      - application/json
      description: Delete Link
      parameters:
      - description: link id
        in: path
        name: link_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Delete Link
      tags:
      - link
  /link/update_link/{link_id}:
    put:
      consumes:
      - application/json
      description: Update Link
      parameters:
      - description: link_id
        in: path
        name: link_id
        required: true
        type: integer
      - description: Link Req
        in: body
        name: LinkReq
        required: true
        schema:
          $ref: '#/definitions/controllers.LinkReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Update Link
      tags:
      - link
  /link_tree/{username}:
    get:
      consumes:
      - application/json
      description: Get Links
      parameters:
      - description: username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrResponse'
      security:
      - basic: []
      summary: Get Links
      tags:
      - link
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
