name: go-test
on:  
  push:
    paths-ignore:
      - 'README.md'

jobs:
  db-test-container:
    runs-on: ubuntu-latest
    container: golang:alpine
    services:
      postgres:
        image: postgres
        ports:
          - 4568:5432
        env:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpassword
            POSTGRES_DB: linktreedbtest
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Run tests
        env:
          DB_TEST_HOST: postgres
          DB_TEST_PORT: 4568
          DB_TEST_USER: admin
          DB_TEST_PASSWORD: testpassword
          DB_TEST_NAME: linktreedbtest
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: cd backend/tests/ && go test